language: node_js
node_js:
- '8'
script: node_modules/.bin/intern
branches:
  only:
  - master
deploy:
  api_key:
    secure: UEmWxJr1X72gsYRtve9HYtzRNrqtN9D7ExjrIWTvBkfUOT7avKQTgH8lQyRr1kLC5YhEAV2UzXHvV/c77uKAFFkQ42TyhDckN2qw44vbZHYlqtJQ8+HnEYZxTpaOoaq3K4UBWuW6rjH3Z2a4cay4xiPhyOT/5ecu8QbQX5OJwMDdG647xQ6M1rd376lwM5mJeZ/VJMORgEDxTbfiT18GUrJ+TXy/29/M8837LhjYxIGORCeo006UameDmDMgSwTph5PN2eIj2e+xJ8kp/f9zyuikSlV0UsUAS6Q71lgRGThxi+KcpKXNGVsPvnqa6E3kkjC3wSymCbSEFi5RXU8zMSEh5iLPaXn3GnYvgglNm8ZSd0wPjhsaJOFz+cnzUaA+sHwP/MJYFHKmhHMKtkhilLewl7AqM2mWv9YcMfHenNGBbP3I1SCSbxgcxJNzmTqYQuLB3+Uz4smu1rQg4qmjcxll3XZC/lrVzcpdan4uftX2fYfa1eWuZuEvKyykYNaFEcCjZWsodLHtF5vHh4v5x5LENI2QD8aF9coCJdU+p46rBd9lKesmQEAdIxX0hjuzo3yT9VtO2qIdroZ+sdL+RAGKhkJmZPxEbzYNk9/uv+dRzU0S46TE9w/+D7OfE7FuQ/xUevMzVqOrywbv9wMnP+yRmW7NSsD17J9Skxo8VEY=
